-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.brands
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT brands_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.cars
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    model_year integer NOT NULL DEFAULT 2023,
    model_name character varying COLLATE pg_catalog."default" NOT NULL,
    brand_id integer NOT NULL,
    price_perkm integer NOT NULL,
    CONSTRAINT cars_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.customer
(
    id integer NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    surname character varying COLLATE pg_catalog."default" NOT NULL,
    identityno character varying(11) COLLATE pg_catalog."default" NOT NULL,
    payment integer NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (identityno)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_date character varying COLLATE pg_catalog."default" NOT NULL,
    start_date character varying COLLATE pg_catalog."default" NOT NULL,
    end_date character varying COLLATE pg_catalog."default" NOT NULL,
    price character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_method
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    ccnumber character varying COLLATE pg_catalog."default" NOT NULL,
    cvv character varying COLLATE pg_catalog."default" NOT NULL,
    ccexdate character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT payment_method_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.cars
    ADD CONSTRAINT "FK_BRAND_CAR" FOREIGN KEY (brand_id)
    REFERENCES public.brands (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT "FK_CAR_CUSTOMER" FOREIGN KEY (id)
    REFERENCES public.cars (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT "FK_CUSTOMER_ORDER" FOREIGN KEY (id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.customer
    ADD CONSTRAINT "FK_Customer_Payment" FOREIGN KEY (payment)
    REFERENCES public.payment_method (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;